version: "3"
services:
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"

  broker:
    build: broker
    environment:
      - SERVER_HOST=activemq
    depends_on:
      - activemq

  dodgydrivers:
    build: dodgydrivers
    environment:
      - SERVER_HOST=activemq
    depends_on:
      - activemq
      - broker

  girlpower:
    build: girlpower
    environment:
      - SERVER_HOST=activemq
    depends_on:
      - activemq
      - broker

  auldfellas:
    build: auldfellas
    environment:
      - SERVER_HOST=activemq
    depends_on:
      - activemq
      - broker
